version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: igaming
      POSTGRES_DB: igaming
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.1.3
    command: >
      redpanda start --overprovisioned --smp 1 --memory 1G --reserve-memory 0M
      --node-id 0 --check=false --kafka-addr 0.0.0.0:9092 --advertise-kafka-addr redpanda:9092
    ports:
      - "9092:9092"
      - "9644:9644"

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    environment:
      - KAFKA_BROKERS=redpanda:9092
    ports:
      - "8080:8080"
    depends_on:
      - redpanda

  minio:
    image: minio/minio:RELEASE.2024-07-10T18-41-49Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

  metabase:
    image: metabase/metabase:v0.49.4
    ports:
      - "3000:3000"
    environment:
      - MB_DB_FILE=/metabase.db
    depends_on:
      - postgres

volumes:
  pgdata: {}
  miniodata: {}
