site_name: iGaming Demo
site_description: "End-to-end streaming → lakehouse → warehouse → BI demo"
site_url: https://nicolaaswanepoel-hue.github.io/igaming-demo/
repo_url: https://github.com/nicolaaswanepoel-hue/igaming-demo
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - attr_list
plugins:
  - search
  - mermaid2    # enables mermaid diagrams
nav:
  - Overview: index.md
  - Architecture: architecture.md
  - Quickstart: quickstart.md
  - Local Dev: local.md
  - Datasets: datasets.md
  - FAQ: faq.md
