site_name: iGaming Demo
site_description: "End-to-end streaming → lakehouse → warehouse → BI demo"
site_url: https://nicolaaswanepoel-hue.github.io/igaming-demo/
repo_url: https://github.com/nicolaaswanepoel-hue/igaming-demo

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight
  - attr_list
  # Enable Mermaid blocks via superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search

# Load Mermaid in the browser + small init script
extra_javascript:
  - https://unpkg.com/mermaid@10.4.0/dist/mermaid.min.js
  - assets/js/mermaid-init.js

nav:
  - Overview: index.md
  - Architecture: architecture.md
  - Quickstart: quickstart.md
  - Local Dev: local.md
  - Datasets: datasets.md
  - FAQ: faq.md
